### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by SUNNYDAY-4176** [scutpaul/DANet#10]
Hi When I run ''train_DAN'.py'  there is a problem, have you ever sew this problem?
Traceback (most recent call last):
  File "H:\Breast_Video\Code\Vedio_Segmentation\DANet-main\train_DAN.py", line 187, in <module>
    train(args)
  File "H:\Breast_Video\Code\Vedio_Segmentation\DANet-main\train_DAN.py", line 75, in train
    transforms=tsfm_train, set_index=args.group)
  File "H:\Breast_Video\Code\Vedio_Segmentation\DANet-main\libs\dataset\YoutubeVOS.py", line 33, in __init__
    self.load_annotations()
  File "H:\Breast_Video\Code\Vedio_Segmentation\DANet-main\libs\dataset\YoutubeVOS.py", line 63, in load_annotations
    self.ytvos = YTVOS(self.ann_file)
  File "C:\Users\siat\.conda\envs\FSVOS\lib\site-packages\pycocotools-2.0-py3.6-win-amd64.egg\pycocotools\ytvos.py", line 59, in __init__
    self.createIndex()
  File "C:\Users\siat\.conda\envs\FSVOS\lib\site-packages\pycocotools-2.0-py3.6-win-amd64.egg\pycocotools\ytvos.py", line 73, in createIndex
    vids[vid['id']] = vid
TypeError: string indices must be integers

**Comment by scutpaul** [comment]
Sorry for replying only now, we didn't meet this error. You can check the pycocotools version: https://github.com/youtubevos/cocoapi.

**Comment by ujaejoon** [comment]
Have you resolved the problem? I am facing the same error.
